source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
#gem 'jekyll-admin', group: :jekyll_plugins
gem 'commonmarker', '0.23.10'
gem 'eventmachine', '1.2.7'

gem "webrick", "~> 1.8"
